version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  db:
    image: "sqlite3"

volumes:
  sqlite-data:
