services:
  web-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    environment:
      - DB_HOST=database
      - DB_NAME=retmind
      - DB_USER=altai
      - DB_PASS=1
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=retmind
      - POSTGRES_USER=altai
      - POSTGRES_PASSWORD=1

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
